### ISSUE TITLE
Icons not show, only description

### ISSUE THREAD

**Issue by betty2310** [Zeioth/wofi-emoji#4]
![](https://scontent.fhan15-2.fna.fbcdn.net/v/t1.15752-9/341933496_602101728524681_5454849699128332763_n.png?_nc_cat=104&ccb=1-7&_nc_sid=ae9488&_nc_ohc=AH3IFqQj6O4AX-Cdrgb&_nc_ht=scontent.fhan15-2.fna&oh=03_AdS22WLA_iseYizDqxLAOVpbfamoo7o1i31z7aEq0HDm1Q&oe=647552BD)

My wofi setting is pure, haven't any config.

**Comment by ayushunofficial** [comment]
add allow_images=true in your wofi config ~/.config/wofi/config
